name: Tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head-commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: npm install --legacy-peer-deps
      - name: run tests
        run: npm run prepush
  
  linter:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: npm install --legacy-peer-deps
      - name: run lint
        run: npm run precommit

  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: deploy on master
  #       run: 